//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int InventoryId { get; set; }
        public string InventoryName { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    }
}
