//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int RoomtypeId { get; set; }
        public int Noofdays { get; set; }
        public int Extensionprice { get; set; }
        public int Pernightprice { get; set; }
    }
}
