//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Code { get; set; }
        public int NoofChildrens { get; set; }
        public Nullable<int> NoofAdults { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public Nullable<System.DateTime> Checkout { get; set; }
        public Nullable<int> NoofRooms { get; set; }
        public string Phno { get; set; }
    }
}
